In [2]:
import numpy as np

array1 = np.arange(100)
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [20]:
array1 = array1.reshape(10,10)
print(array1)
#first value is the row and second is the column
print(array1[1][3])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
13


In [21]:
#reshape to 3 dimentional array
array1 = array1.reshape(5,4,5)
print(array1)


[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]

 [[60 61 62 63 64]
  [65 66 67 68 69]
  [70 71 72 73 74]
  [75 76 77 78 79]]

 [[80 81 82 83 84]
  [85 86 87 88 89]
  [90 91 92 93 94]
  [95 96 97 98 99]]]


In [25]:
print(array1[4])
print(array1[0][1])
print(array1[0][1][2])

[[80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]]
[5 6 7 8 9]
7


In [26]:
#array operations
array1 = np.arange(100)
array1 = array1.reshape(5,4,5)
print(array1)

array2 = np.arange(100)
array2 = array2.reshape(5,4,5)
print(array2)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]

 [[60 61 62 63 64]
  [65 66 67 68 69]
  [70 71 72 73 74]
  [75 76 77 78 79]]

 [[80 81 82 83 84]
  [85 86 87 88 89]
  [90 91 92 93 94]
  [95 96 97 98 99]]]
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]

 [[60 61 62 63 64]
  [65 66 67 68 69]
  [70 71 72 73 74]
  [75 76 77 78 79]]

 [[80 81 82 83 84]
  [85 86 87 88 89]
  [90 91 92 93 94]
  [95 96 97 98 99]]]


In [27]:
array3 = np.add(array1,array2)
print(array3)

[[[  0   2   4   6   8]
  [ 10  12  14  16  18]
  [ 20  22  24  26  28]
  [ 30  32  34  36  38]]

 [[ 40  42  44  46  48]
  [ 50  52  54  56  58]
  [ 60  62  64  66  68]
  [ 70  72  74  76  78]]

 [[ 80  82  84  86  88]
  [ 90  92  94  96  98]
  [100 102 104 106 108]
  [110 112 114 116 118]]

 [[120 122 124 126 128]
  [130 132 134 136 138]
  [140 142 144 146 148]
  [150 152 154 156 158]]

 [[160 162 164 166 168]
  [170 172 174 176 178]
  [180 182 184 186 188]
  [190 192 194 196 198]]]


In [28]:
array3 = np.multiply(array1,array2)
print(array3)

[[[   0    1    4    9   16]
  [  25   36   49   64   81]
  [ 100  121  144  169  196]
  [ 225  256  289  324  361]]

 [[ 400  441  484  529  576]
  [ 625  676  729  784  841]
  [ 900  961 1024 1089 1156]
  [1225 1296 1369 1444 1521]]

 [[1600 1681 1764 1849 1936]
  [2025 2116 2209 2304 2401]
  [2500 2601 2704 2809 2916]
  [3025 3136 3249 3364 3481]]

 [[3600 3721 3844 3969 4096]
  [4225 4356 4489 4624 4761]
  [4900 5041 5184 5329 5476]
  [5625 5776 5929 6084 6241]]

 [[6400 6561 6724 6889 7056]
  [7225 7396 7569 7744 7921]
  [8100 8281 8464 8649 8836]
  [9025 9216 9409 9604 9801]]]


In [29]:
array3 = np.subtract(array1,array2)
print(array3)

[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]


In [30]:
array3 = np.minimum(array1,array2)
print(array3)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]

 [[60 61 62 63 64]
  [65 66 67 68 69]
  [70 71 72 73 74]
  [75 76 77 78 79]]

 [[80 81 82 83 84]
  [85 86 87 88 89]
  [90 91 92 93 94]
  [95 96 97 98 99]]]


In [31]:
#transpose of array
array1 = np.arange(10).reshape(2,5)
print(array1)


[[0 1 2 3 4]
 [5 6 7 8 9]]


In [33]:
print(array1.transpose())

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


### statistic operations

In [34]:
print(array1.sum())

45


In [35]:
print(array1.mean())


4.5


In [36]:
print(array1.std())

2.8722813232690143


In [37]:
print(array1.var())

8.25


### where statement for array

In [38]:
print(array1)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [39]:
array2 = np.where(array1<3,0,array1)
print(array2)

[[0 0 0 3 4]
 [5 6 7 8 9]]


In [4]:
arr=np.ones(9)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
arr=np.ones(10).reshape(2,5)
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
np.zeros(20).reshape(5,4)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
np.random.randint(2,10) # randomly generate values between 2 to 10

9

In [16]:
np.random.randint(2,50,8) # randomly generate 8 values between 2 and 50

array([32, 48, 34, 36,  9, 10, 23, 15])

In [18]:
np.random.randint(2,1000,8)

array([459, 745, 104,  62, 524, 126, 250, 946])

In [19]:
np.random.random_sample(5) # generates vaalues between random sample distribution

array([0.23140235, 0.22741399, 0.83166224, 0.99919191, 0.95586618])

In [23]:
np.random.random_sample(7)

array([0.56341346, 0.78625844, 0.76488986, 0.58362684, 0.49587648,
       0.54629927, 0.18345334])

In [25]:
np.random.randn(5) #randomly generates values between random normal distribution

array([0.08974236, 0.48094359, 0.13732112, 1.06083525, 0.28261753])

In [26]:
np.random.randn(5,4)

array([[ 1.04372087,  0.47919981, -2.26956133, -0.16791732],
       [-1.30577403, -0.1784166 , -2.1620773 ,  0.15292374],
       [ 1.18674192, -1.36517004, -1.41362523,  0.17860774],
       [ 1.64276694,  1.36078824,  0.78707974, -0.6507965 ],
       [ 1.46057996,  1.02216811, -0.71483549,  0.03288781]])

In [27]:
np.random.rand(5) #generates values between (uniform distribution)

array([0.36052521, 0.43184588, 0.65030564, 0.64608058, 0.08245756])

In [34]:
np.empty(2)

array([-1.62088251e-221,  2.75738661e+120])

In [35]:
np.full((3,2),8)

array([[8, 8],
       [8, 8],
       [8, 8]])

In [36]:
a=np.arange(0,30,2).reshape(3,5)
a

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [37]:
print(a.shape)
print(a.dtype)
print(a.ndim)
print(a.size)
print(a.dtype.name)
print(type(a))
print(a.itemsize)

(3, 5)
int32
2
15
int32
<class 'numpy.ndarray'>
4


In [38]:
a.transpose()

array([[ 0, 10, 20],
       [ 2, 12, 22],
       [ 4, 14, 24],
       [ 6, 16, 26],
       [ 8, 18, 28]])

In [39]:
print(a.shape)
print(a.dtype)
print(a.ndim)
print(a.size)
print(a.dtype.name)
print(type(a))
print(a.itemsize)

(3, 5)
int32
2
15
int32
<class 'numpy.ndarray'>
4


In [40]:
np.linspace(0, 2, 9)                   # 9 numbers from 0 to 2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [41]:
np.linspace(0,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747