In [1]:
import numpy as np

array1 = np.array([4,6,8,9])
print(array1)

[4 6 8 9]


In [2]:
array1 = np.arange(10)
print(array1)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
array2 = array1.reshape(2,5)
print(array2)
print(array2.shape)
print(array2.dtype.name)
print(array2.ndim)
print(array2.size)

[[0 1 2 3 4]
 [5 6 7 8 9]]
(2, 5)
int32
2
10


# # Convert list to numpy array

In [4]:
months = ['jan', 'mar', 'apr', 'jun']
months_arr = np.array(months)
print(months_arr)
months_arr

['jan' 'mar' 'apr' 'jun']


array(['jan', 'mar', 'apr', 'jun'], dtype='<U3')

In [5]:
months = ['jan', 'mar', 'apr', 'jun',['aug','sep','nov']]
months_arr = np.array(months)
print(months_arr)
months_arr

['jan' 'mar' 'apr' 'jun' list(['aug', 'sep', 'nov'])]


C:\Users\temp\AppData\Local\Temp\ipykernel_14876\573888028.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  months_arr = np.array(months)


array(['jan', 'mar', 'apr', 'jun', list(['aug', 'sep', 'nov'])],
      dtype=object)

### create zero array and unity array

In [6]:
array2 = np.zeros(100)
array2 = array2.reshape(10,10)
print(array2)

array2 = np.ones(100)
array2 = array2.reshape(10,10)
print(array2)

#generating identity array
array2 = np.eye(6)
array2 = array2.reshape(6,3,2)
print(array2)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[[1. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 1.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [1. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 1.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [1. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 1.]]]


## empty and full array

In [7]:
array3 = np.empty((3,2))
print(array3)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [8]:
array3 = np.full((3,2),1)
print(array3)

[[1 1]
 [1 1]
 [1 1]]
