In [1]:
import numpy as np

array1 = np.random.random((2,3))
print(array1)

[[0.56013528 0.20044529 0.97459015]
 [0.3578801  0.65808244 0.43582719]]


In [2]:
array2 = np.random.random((2,3))
print(array2)

[[0.34875372 0.19096121 0.77534509]
 [0.03715932 0.77595984 0.01313518]]


### Array operations 

In [3]:
array3 = array1+array2
print(array3)

[[0.908889   0.3914065  1.74993525]
 [0.39503942 1.43404228 0.44896238]]


In [4]:
array3 = array1-array2
print(array3)

[[ 0.21138156  0.00948409  0.19924506]
 [ 0.32072078 -0.1178774   0.42269201]]


In [5]:
array3 = array1*array2
print(array3)

[[0.19534926 0.03827728 0.75564369]
 [0.01329858 0.51064554 0.00572467]]


In [6]:
array3 = array1/array2
print(array3)

[[ 1.60610553  1.04966499  1.25697597]
 [ 9.63096461  0.84808828 33.18013419]]


In [7]:
array4 = np.arange(5)
print(array4)
array4 = array4 ** 2
print(array4)

[0 1 2 3 4]
[ 0  1  4  9 16]


## numpy array indexing 

In [8]:
array5 = np.arange(10)
array5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
array5[4] = 7
print(array5[4])
print(array5)

7
[0 1 2 3 7 5 6 7 8 9]


In [10]:
print(array5[2:5])

[2 3 7]


In [11]:
print(array5[:])

[0 1 2 3 7 5 6 7 8 9]


In [12]:
print(array5[:5])
print(array5[2:])

[0 1 2 3 7]
[2 3 7 5 6 7 8 9]


In [13]:
array5[:5] = 1
print(array5)

[1 1 1 1 1 5 6 7 8 9]


In [14]:
array6= array5.copy()
print(array6)

[1 1 1 1 1 5 6 7 8 9]
